config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :news

  match 'Home', to: 'news#Home', via: 'get'

  match 'signout', to:'news#signout',via: 'delete'

match 'subscribe', to:'categories#subscribe',via:'post'

  root 'news#index'

end

app/models/news.rb
class News < ActiveRecord::Base

  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /news
  # GET /news.json
  def index
@user_id=current_user.id

@present_user=User.find(@user_id)

@User_categories=@present_user.categories







    @news = News.all

  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
    @all_categories= Category.all
    @news_category=@news.categories.build
  end

  # GET /news/1/edit
  def edit
    @all_categories= Category.all
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    params[:category][:id].each do |e|

      if !e.empty?

        a=Category.find(e)
        @news.categories << a
      end
    end

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
     if  @news.update(news_params)




        params[:category][:id].each do |e|

          if !e.empty?

            a=Category.find(e)
            @news.categories << a
          end
        end



        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def Home


  end


  def signout

    sign_out :user
  end

  def header


  end

  def category
@category=Category.new
  end

  def cat

  end

  def subscribe

    @category=Category.new(:name=>params[:name],:description=>params[:description])

    redirect_to 'news/Success'

  end

  def Success


  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title,:subject,:content)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/Home.html.erb
<h1> Home Page</h1>

app/views/news/Success.html.erb
<h1>syccessfully created</h1>

app/views/news/_cat.html.erb
<div id="catgoryform">

 <%= form_for @category, url: 'subscribe'  do |f| %>
     <%= f.text_field :name %>
     <%= f.text_area :description, size: "60x12" %>
     <%= f.submit 'Create' %>
 <% end %>
</div>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="news_article_title">
    <%= f.label :Title %><br>
    <%= f.text_field :title%>
  </div>
    <div class="field" id="news_article_subject">
     <%= f.label :Subject %><br>
     <%= f.text_field :subject%>
    </div>
    <div class="field" id="news_article_content">
     <%= f.label :Content %><br>
     <%= f.text_field :content%>
    </div>

    <div class="field" id="news_category">
     <%= f.label :Category %><br>
     <%= collection_select(:category,:id,@all_categories, :id, :name,{},{:multiple => true})%>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/_header.html.erb
<nav class="navbar navbar-inverse">
 <div class="container-fluid">
  <div class="navbar-header">
   <a class="navbar-brand" href="#">Twitter Clone</a>
  </div>
  <ul class="nav navbar-nav">
   <li class="active"><a href="#">Home</a></li>
   <li><a href='categories'>Channels</a></li>
   <li><a href="#">Page 2</a></li>
   <li><a href="#">Page 3</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">

   <% if user_signed_in? %>
   <li> <%= link_to('<span class="glyphicon glyphicon-user">SignOut</span>'.html_safe, destroy_user_session_path, :method => :delete) %></li>
   <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Settings</a></li>

       <%else%>
       <li> <%= link_to('<span class="glyphicon glyphicon-user">SignIn</span>'.html_safe, new_user_session, :method => :delete) %></li>

       <% end %>
  </ul>
 </div>
</nav>

app/views/news/category.html.erb
<div class="container">
 <div class="center-block">

  <%= render 'news/cat' %>
 </div>

</div>

app/views/news/edit.html.erb
<h1>Edit News</h1>

<%= render 'form' %>
<h1> this is the file i have changed</h1>
<h2> this is the one wo</h2>

<h3>edit Page</h3>
<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'news/header' %>

<div class="container">


 <div class="jumbotron">
  <h1 style="text-align: center">News</h1>

 </div>
 <div class="row">

  <% @User_categories.each do |news| %>

      <% news.news.each do |n|%>
  <div class="col-sm-3 back_texture">

   <h3><%= n.title %></h3>
   <hr>
   <p style="text-align: center"><%=n.subject%></p>
  </div>
          <%end%>
             <%end%>

 </div>

 <div class="row">
  <div class="col-xs-3 col-md-3"></div>
  <div class="col-xs-3 col-md-3 btn btn-default" ><%= link_to 'New News', new_news_path %></div>
 </div>
</div>
</html>

app/views/news/new.html.erb
<%= render 'news/header' %>

<%= render 'form' %>
<%= link_to 'create_category',new_category_url %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>